#!/usr/bin/env bash
# init_repo.sh — rename placeholder_name to the actual package name.
# Run once after cloning the template. Safe to re-run (idempotent).
set -euo pipefail

# ---------------------------------------------------------------------------
# Resolve repo root and derive package name
# ---------------------------------------------------------------------------
REPO_ROOT=$(dirname "$(dirname "$(realpath "$0")")")
PACKAGE_NAME=$(basename "$REPO_ROOT" | tr '-' '_')

echo "🚀  Initializing: $(basename "$REPO_ROOT") → package: $PACKAGE_NAME"
cd "$REPO_ROOT"

if [ "$PACKAGE_NAME" = "placeholder_name" ]; then
    echo "⚠️  Package name is still 'placeholder_name' — rename the repo directory first."
    exit 1
fi

# ---------------------------------------------------------------------------
# Helper: replace every occurrence of placeholder_name in a single file
# ---------------------------------------------------------------------------
replace_in_file() {
    local file="$1"
    [ -f "$file" ] || return 0
    python3 - "$file" "$PACKAGE_NAME" <<'PY'
import sys
path, pkg = sys.argv[1], sys.argv[2]
content = open(path).read()
updated = content.replace("placeholder_name", pkg)
if content != updated:
    open(path, "w").write(updated)
    print(f"  ✏️  {path}")
PY
}

# ---------------------------------------------------------------------------
# 1. Rename src package directory
# ---------------------------------------------------------------------------
if [ -d "src/placeholder_name" ]; then
    mv "src/placeholder_name" "src/$PACKAGE_NAME"
    echo "📂  src/placeholder_name → src/$PACKAGE_NAME"
fi

# ---------------------------------------------------------------------------
# 2. Delete stale build artifacts (will be regenerated by uv sync)
# ---------------------------------------------------------------------------
rm -rf src/placeholder_name.egg-info

# ---------------------------------------------------------------------------
# 3. Replace in all text endpoints
# ---------------------------------------------------------------------------
echo "🔄  Replacing imports and references..."

# pyproject.toml — covers: name, root_packages, source_modules, forbidden_modules
replace_in_file pyproject.toml

# entry point
replace_in_file main.py

# Claude Code hooks — smoke check and other hook scripts may reference the package name
replace_in_file .claude/settings.json

# all Python sources and tests
while IFS= read -r -d '' f; do
    replace_in_file "$f"
done < <(find src tests -name "*.py" -type f -print0 2>/dev/null)

# ---------------------------------------------------------------------------
# 4. Install / sync dependencies
# ---------------------------------------------------------------------------
if ! command -v uv &>/dev/null; then
    echo "❌  uv not found — install it first: https://docs.astral.sh/uv/getting-started/installation/"
    exit 1
fi

echo "📦  Syncing dependencies..."
uv sync

# ---------------------------------------------------------------------------
# 5. Pre-commit hooks
# ---------------------------------------------------------------------------
echo "🪝  Installing pre-commit hooks..."
uv run pre-commit install

# ---------------------------------------------------------------------------
# 6. Regenerate secrets baseline (file paths have changed)
# ---------------------------------------------------------------------------
echo "🔐  Regenerating secrets baseline..."
uv run detect-secrets scan --exclude-files 'uv\.lock|\.git' > .secrets.baseline

# ---------------------------------------------------------------------------
# 7. Bootstrap .env
# ---------------------------------------------------------------------------
if [ -f ".env.example" ] && [ ! -f ".env" ]; then
    cp .env.example .env
    echo "🔑  Created .env from .env.example"
fi

echo ""
echo "✅  Done! Package: $PACKAGE_NAME"
echo "    Run 'uv run python main.py' to verify the setup."
